'''
Code for the implementation of
"Spatially-Variant CNN-based Point Spread Function Estimation for Blind Deconvolution and Depth Estimation in Optical Microscopy"

Copyright (c) 2020 Idiap Research Institute, https://www.idiap.ch/
Written by Adrian Shajkofci <adrian.shajkofci@idiap.ch>,
All rights reserved.

This file is part of Spatially-Variant CNN-based Point Spread Function Estimation.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. Neither the name of mosquitto nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
'''


import numpy as np
from matplotlib import pyplot as plt
from sklearn.metrics import r2_score
import math


# Parameters of the microscope
degrees_inclination = 6
radians_inclination = degrees_inclination * math.pi / 180.
resolution = 0.32
size = 2048
num_cases = 16
max_view = resolution*size #micrometers 0.32 micron per pixel * 2048 pixel
max_depth = max_view * math.tan(radians_inclination)
print('Max depth : {} um'.format(max_depth))

# This file is generated by test_plane_stats
table = np.load('feat13.npy')
x = np.linspace(0,num_cases,num_cases)
table = table[:,1::128]
y = table.mean(axis=0)

alpha = max_depth / (y.max()-y.min())
y = y*alpha
x = x*max_view/num_cases

print('Y range :{}'.format((y.max()-y.min())))


var = table.var(axis=0)
fit = np.polyfit(x,y,1)
fit_fn = np.poly1d(fit)
fitted_x = fit_fn(x)
rsquare = r2_score(y, fitted_x)
error = ((y - fitted_x).__abs__()).mean()
plt.figure(dpi=300, figsize=(6,3))
plt.plot(x,y, '.', x, fitted_x, '--k')
plt.title(r'$R^2=$' + '{:0.3f} / error = {:0.5f}'.format(rsquare, error))
plt.xlabel('Y direction in the input image [microns]')
plt.ylabel('Depth [microns]')
plt.errorbar(x,y,yerr=var*max_view)
plt.show()